# Makefile for the shell util subsystem

all: arch whoami yes

yes: yes.rs
	$(COMPILER) $(CFLAGS) yes.rs

whoami: whoami.rs
	$(COMPILER) $(CFLAGS) whoami.rs

arch: arch.rs
	$(COMPILER) $(CFLAGS) arch.rs
